### ISSUE TITLE
3d modeling: promo

### ISSUE THREAD

**Issue by amra** [innovation-lab-prague/presentations#15]
Do the promotion of 3d printing presentation on 25.7. like email, leaflets, slack, ...

**Comment by StanSiska** [comment]
Presentation postponed to 1.8.

**Comment by StanSiska** [comment]
Promo prepared - leafleats, Slack prepared. Would like to avoid emails this time as redundant option.

**Comment by amra** [comment]
Aleš's move to USA did interfere with the presentation date. So the presentation was canceled.
